global:
  # slack_api_url: https://hooks.slack.com/services/xxxxxxx/xxxxxxxx/xxxxxxx  # this is for Incoming Webhooks
  slack_api_url: https://slack.com/api/chat.postMessage  # if using slack api need give bearer_token
  resolve_timeout: 1m
  smtp_from: alertmanager@email.com
  smtp_smarthost: <smtphost>
  smtp_auth_username: <username>
  smtp_auth_password: <password>


# The root node of the routing tree.
route:
  receiver: 'null'
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 1m
  routes:
    - receiver: 'email'
      group_by: ['service', 'severity']
      continue: true
      match_re:
        severity: critical|warning
    - receiver: 'slack'
      group_by: ['service', 'severity']
      continue: true
      match_re:
        alertname: RedisTooManyKeys|PrometheusAlertPagesRequestsCount


# A list of notification receivers.
receivers:
  - name: 'null'
  - name: 'slack'
    slack_configs:
      - channel: 'error'
        username: 'alertmanager'
        icon_emoji: ':fire:'
        title: "[{{ .CommonLabels.severity }}]: {{ .CommonAnnotations.summary }}"
        text: "{{ .CommonLabels.service }}: \n {{ .CommonAnnotations.description }} \n {{ .Alerts }}"
        http_config:  # for slack api setting
          bearer_token: <token>
  - name: 'email'
    email_configs:
      - to: 'demo@email.com'


# A list of inhibition rules.
# inhibit_rules:
#   - 
